### ISSUE TITLE
vendors bug

### ISSUE THREAD

**Issue by landsman** [mrtnzlml/CMS-lite#1]
Ahoj objevil jsem následující bug
![vendors](https://cloud.githubusercontent.com/assets/3184228/11702512/88e18d3c-9ed7-11e5-9394-914378da37cc.PNG)

**Comment by mrtnzlml** [comment]
Mrkni na to teď, snad jsem tím něco nerozbil...

**Comment by landsman** [comment]
Zkusil jsem:
![image](https://cloud.githubusercontent.com/assets/3184228/11718493/8264e2f4-9f56-11e5-81cb-df1ba37d023a.png)

**Comment by mrtnzlml** [comment]
Před chvílí jsem to zkoušel celé nainstalovat znova a šlo to, takže bych to spíš sázel na to co to píše, tedy `the requested PHP extension curl is missing from your system`. Nechybí ti tedy curl rozšíření?

Případně můžeš tu řádku s `kdyby/tester-extras` smazat. Používá se to jen u testů...

**Comment by landsman** [comment]
Zřejmě na localu chybí, doinstaluji. Bez ní to už vendory stáhlo, díky! :+1:
