### ISSUE TITLE
Install SQL error: table pages: Error Code: 1214. The used table type doesn't support FULLTEXT indexes

### ISSUE THREAD

**Issue by steinbauer** [mrtnzlml/CMS-lite#2]
**SQL: (via `php index.php orm:schema-tool:create --dump-sql` )**
`CREATE TABLE pages (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, url_id INT DEFAULT NULL, locale_id INT DEFAULT NULL, title LONGTEXT NOT NULL COMMENT 'Title of the article', individual_title LONGTEXT DEFAULT NULL COMMENT 'Meta title of the article', description LONGTEXT DEFAULT NULL COMMENT 'Meta description of the article', body LONGTEXT NOT NULL COMMENT 'Body of the article', `index` VARCHAR(255) DEFAULT NULL COMMENT 'Meta robots - index value', follow VARCHAR(255) DEFAULT NULL COMMENT 'Meta robots - follow value', created_at DATETIME NOT NULL COMMENT 'Date of the article creation', published_at DATETIME DEFAULT NULL COMMENT 'Date of the article publication', individual_css_id VARCHAR(255) DEFAULT NULL COMMENT 'Individual CSS IDs in body element', individual_css_class VARCHAR(255) DEFAULT NULL COMMENT 'Individual CSS classes in body element', protected TINYINT(1) NOT NULL COMMENT 'Is this page protected by password?', password VARCHAR(255) DEFAULT NULL, deleted TINYINT(1) DEFAULT '0' NOT NULL, INDEX IDX_2074E575A76ED395 (user_id), UNIQUE INDEX UNIQ_2074E57581CFDAE7 (url_id), INDEX IDX_2074E575E559DFD1 (locale_id), FULLTEXT INDEX IDX_2074E5752B36786B (title), FULLTEXT INDEX IDX_2074E575DBA80BB2 (body), FULLTEXT INDEX IDX_2074E5752B36786BDBA80BB2 (title, body), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB`    

**Error:**
`Error Code: 1214. The used table type doesn't support FULLTEXT indexes`

---

**reason?**
? LONGTEXT and Fulltext index ?
? InnoDB and Fulltext index ?

**Comment by mrtnzlml** [comment]
Probably wrong MySQL version. See [minimum requirements](https://github.com/mrtnzlml/CMS-lite/blob/master/readme.md)...

**Comment by steinbauer** [comment]
Y, that's it.
Thank you!
